services:
  database:
    image: postgres
    container_name: database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: database
    networks:
      - network
    ports:
      - "9578:5432"
    volumes:
      - database_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./Backend
    container_name: backend
    ports:
      - "9876:9876"
    networks:
      - network
    depends_on:
      - database
    environment:
      - SPRING_PROFILES_ACTIVE=dev
#      - SPRING_PROFILES_ACTIVE=prod

  frontend:
    build:
      context: ./Frontend
    container_name: frontend
    ports:
      - "4300:4300"
    networks:
      - network


networks:
  network:
    driver: bridge

volumes:
  database_data: